language: java
jdk: oraclejdk8

addons:
  postgresql: 9.4

before_install:
  - mkdir /tmp/output
  - ln -snf test/travis/maven-config.properties ./maven-config.properties

install:
  - psql -U postgres -c 'create database travis_ci_test;'
  - psql -U postgres -d travis_ci_test < test/sql/companydata.sql

script:
  - mvn clean install --settings test/travis/maven-config.xml

  # Test Coverage
  - mvn coveralls:cobertura

  # Deploy artifacts
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn deploy --settings travis-mvn-config.xml ; fi

  # Trick to avoid useless S3 cache updates
  - mv $HOME/.m2/repository/ch/alv /tmp/cache-trick

cache:
  directories:
    - '$HOME/.m2/repository'
