sudo: required
dist: trusty
services:
  - docker

language: java
jdk:
  - oraclejdk8
#  - openjdk8

env:
  global:
    - MAVEN_ARGS="--settings test/travis/maven-config.xml"
    - MAVEN_ARGS_SKIP_TESTS="$MAVEN_ARGS -DskipTests=true"

# Disabled, because File Caching is only available on Docker-based environment
# cache:
#   directories:
#     - '$HOME/.m2/repository'

before_install:
  - pip install --user codecov

  # stop default PostgreSQL service (port conflict)
  - sudo service postgresql stop

  # create and initialize docker-based services
  - ./test/travis/create-docker-containers.sh
  - ./test/sql/master/create-master-db-schema.sh
  - ./test/elasticsearch/create-jobdesk-index.sh

install:
  - mvn clean install $MAVEN_ARGS_SKIP_TESTS

script:
  - mvn test $MAVEN_ARGS

  # Publish the Artifacts built from master branch
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean deploy $MAVEN_ARGS_SKIP_TESTS ; fi

# DISABLED, because S3 caching is only available in docker-based environment
#
#   # Trick to avoid useless S3 cache updates
#   # (force this step to always return 0, as it might fail for some unkown reasons, so far...)
#   - mv $HOME/.m2/repository/ch/alv /tmp/cache-trick || /bin/true

after_success:
  - codecov

notifications:
  webhooks:
    # trigger Buildtime Trend Service to parse Travis CI log
    - https://buildtimetrend.herokuapp.com/travis
