language: java
jdk: oraclejdk8

addons:
  postgresql: 9.4

env:
  global:
    - MAVEN_DEPLOY_ARGS="--settings test/travis/maven-config.xml -DskipTests=true"

before_install:
  - mkdir /tmp/output
  - ln -snf test/travis/maven-config.properties ./maven-config.properties

install:
  - psql -U postgres -c 'create database travis_ci_test;'
  - psql -U postgres -d travis_ci_test < test/sql/master/company.sql
  - psql -U postgres -d travis_ci_test < test/sql/master/partnerjob.sql
  - cp test/travis/application.yml master/company/src/test/resources/application.yml
  - cp test/travis/application.yml master/partnerjob/src/test/resources/application.yml

script:
  - mvn clean cobertura:cobertura coveralls:report

  # Rebuild without Cobertura Instrumentation and Upload the built Artifacts
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean deploy $MAVEN_DEPLOY_ARGS ; fi

  # Trick to avoid useless S3 cache updates
  - mv $HOME/.m2/repository/ch/alv /tmp/cache-trick

cache:
  directories:
    - '$HOME/.m2/repository'
