language: java

jdk: oraclejdk8

addons:
  postgresql: 9.4

env:
  global:
    - TEST_DB_NAME=travis_ci_test
    - TEST_DB_USERNAME=postgres
    - TEST_DB_PASSWORD=
    - MAVEN_DEPLOY_ARGS="--settings test/travis/maven-config.xml -DskipTests=true"

install:
  - ./test/travis/build-test-database.sh
  - ./replace-db-settings.sh

script:
  - mvn clean cobertura:cobertura coveralls:report

  # Rebuild without Cobertura Instrumentation and Upload the built Artifacts
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean deploy $MAVEN_DEPLOY_ARGS ; fi

  # Trick to avoid useless S3 cache updates
  - mv $HOME/.m2/repository/ch/alv /tmp/cache-trick

cache:
  directories:
    - '$HOME/.m2/repository'
