sudo: required
dist: trusty
group: edge

services:
  - docker

#language: java
jdk: oraclejdk9

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_ARGS="--settings test/travis/maven-config.xml"
    - MAVEN_DEPLOY_ARGS="$MAVEN_ARGS -DskipTests=true"

before_install:
  - sudo apt-get sudo apt-get update -qq
  - sudo apt-get install --only-upgrade -y oracle-java9-installer

install:

  # login to pull private docker images
  # - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_PRIVATE_REPO

  # stop default PostgreSQL service (port conflict)
  - sudo service postgresql stop

  # create and initialize docker-based services
  - ./test/travis/create-docker-containers.sh
  - ./test/sql/master/create-master-db-schema.sh
  - ./test/elasticsearch/create-jobdesk-index.sh

script:
  - mvn clean cobertura:cobertura coveralls:report $MAVEN_ARGS

  # Rebuild without Cobertura Instrumentation and Upload the built Artifacts
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean deploy $MAVEN_DEPLOY_ARGS ; fi

#   # Trick to avoid useless S3 cache updates
#   # (force this step to always return 0, as it might fail for some unkown reasons, so far...)
#   - mv $HOME/.m2/repository/ch/alv /tmp/cache-trick || /bin/true

# cache:
#   directories:
#     - '$HOME/.m2/repository'

