/**
 * This class is generated by jOOQ
 */
package ch.alv.batches.master.to.jobdesk.model;


import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * DTO representing a jobdesk job.
 *
 * @since 1.0.0
 */
public class JobdeskJob implements Serializable {

    private static final long serialVersionUID = -1972325289;

    private String jobId;

    private String jobIdAvam;

    private String jobIdEgov;

    private String url;

    private JobdeskMultiLanguageValue title;

    private JobdeskMultiLanguageValue description;

    private Date startDate;

    private Date endDate;

    private int quotaFrom;

    private int quotaTo;

    private JobdeskJobLocation location;

    private JobdeskJobApplication application;

    private JobdeskJobCompany company;

    private JobdeskJobContact contact;

    private List<JobdeskLanguage> languages = new ArrayList<>();

    private boolean fulltime;

    private boolean external;

    private Date publicationDate;

    private JobdeskIscoCode isco;

    private String source;

    public String getJobId() {
        return jobId;
    }

    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * fingerprint is an alias to jobId
     */
    public String getFingerprint() {
        return getJobId();
    }

    /**
     * fingerprint is an alias to jobId
     */
    public void setFingerprint(String fingerprint) {
        // NOOP
    }

    public String getJobIdAvam() {
        return jobIdAvam;
    }

    public void setJobIdAvam(String jobIdAvam) {
        this.jobIdAvam = jobIdAvam;
    }

    public String getJobIdEgov() {
        return jobIdEgov;
    }

    public void setJobIdEgov(String jobIdEgov) {
        this.jobIdEgov = jobIdEgov;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public JobdeskMultiLanguageValue getTitle() {
        return title;
    }

    public void setTitle(JobdeskMultiLanguageValue title) {
        this.title = title;
    }

    public JobdeskMultiLanguageValue getDescription() {
        return description;
    }

    public void setDescription(JobdeskMultiLanguageValue description) {
        this.description = description;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public int getQuotaFrom() {
        return quotaFrom;
    }

    public void setQuotaFrom(int quotaFrom) {
        this.quotaFrom = quotaFrom;
    }

    public int getQuotaTo() {
        return quotaTo;
    }

    public void setQuotaTo(int quotaTo) {
        this.quotaTo = quotaTo;
    }

    public JobdeskJobLocation getLocation() {
        return location;
    }

    public void setLocation(JobdeskJobLocation location) {
        this.location = location;
    }

    public JobdeskJobApplication getApplication() {
        return application;
    }

    public void setApplication(JobdeskJobApplication application) {
        this.application = application;
    }

    public JobdeskJobCompany getCompany() {
        return company;
    }

    public void setCompany(JobdeskJobCompany company) {
        this.company = company;
    }

    public JobdeskJobContact getContact() {
        return contact;
    }

    public void setContact(JobdeskJobContact contact) {
        this.contact = contact;
    }

    public List<JobdeskLanguage> getLanguages() {
        return languages;
    }

    public void setLanguages(List<JobdeskLanguage> languages) {
        this.languages = languages;
    }

    public boolean isFulltime() {
        return fulltime;
    }

    public void setFulltime(boolean fulltime) {
        this.fulltime = fulltime;
    }

    public boolean isExternal() {
        return external;
    }

    public void setExternal(boolean external) {
        this.external = external;
    }

    public Date getPublicationDate() {
        return publicationDate;
    }

    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }

    public JobdeskIscoCode getIsco() {
        return isco;
    }

    public void setIsco(JobdeskIscoCode isco) {
        this.isco = isco;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }
}
