# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.network "forwarded_port", guest: 5432, host: 5432

#  config.vm.provider "virtualbox" do |vb|
#    vb.memory = 1024
#    vb.cpus = 1
#  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define 'master_db' do |machine|
    machine.vm.box = 'geerlingguy/ubuntu1404'

    machine.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.galaxy_role_file  = "galaxy.yml"
    end
  end

end
