/**
 * This class is generated by jOOQ
 */
package ch.alv.batches.commons.sql.jooq;


import ch.alv.batches.commons.sql.jooq.tables.TestJooq;
import ch.alv.batches.commons.sql.jooq.tables.records.TestJooqRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>JOBROOM</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TestJooqRecord> SYS_C0011148 = UniqueKeys0.SYS_C0011148;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TestJooqRecord> SYS_C0011148 = createUniqueKey(TestJooq.TEST_JOOQ, "SYS_C0011148", TestJooq.TEST_JOOQ.ID);
    }
}
