/**
 * This class is generated by jOOQ
 */
package ch.alv.batches.commons.sql.jooq;


import ch.alv.batches.commons.sql.jooq.tables.TestJooq;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in JOBROOM
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>JOBROOM.TEST_JOOQ</code>.
     */
    public static final TestJooq TEST_JOOQ = ch.alv.batches.commons.sql.jooq.tables.TestJooq.TEST_JOOQ;
}
